name: PHPUnit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      dev-ops-analyze-directory: ${{ github.workspace }}/dev-ops/analyze
      plugin-directory: ${{ github.workspace }}/custom/plugins/plugin
    strategy:
      fail-fast: false
      matrix:
        shopware-versions:
          - v6.4.8.2
          - v6.4.9.0
          - v6.4.10.1
          - v6.4.11.1
          - v6.4.12.0
          - v6.4.13.0
          - v6.4.14.0
          - v6.4.15.2
          - v6.4.16.1
          - v6.4.17.2
          - v6.4.18.1
          - v6.4.19.0
          - v6.4.20.2

    steps:
      - name: Clone Shopware repository
        uses: actions/checkout@v4
        with:
          repository: shopware/development
          ref: ${{ matrix.shopware-versions }}

      # Update outdated lock file
      - name: Update DevOps dependencies
        working-directory: ${{ env.dev-ops-analyze-directory }}
        run: composer update

      - name: Install Shopware dependencies
        run: |
          composer require "shopware/platform:${{ matrix.shopware-versions }}" --no-update
          ./psh.phar init-composer

      - name: Checkout plugin
        uses: actions/checkout@v4
        with:
          path: ${{ env.plugin-directory }}

      - name: Install plugin dependencies
        working-directory: ${{ env.plugin-directory }}
        run: |
          composer validate --strict
          composer install --no-interaction

      - name: Run PHPUnit tests
        working-directory: ${{ env.plugin-directory }}
        run: composer run-script test:coverage-clover

      - name: Check code coverage
        working-directory: ${{ env.plugin-directory }}
        run: |
          composer require --dev michaelmoussa/php-coverage-checker
          ./vendor/bin/php-coverage-checker coverage/clover.xml 100

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage/clover.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
